export type FrontendVitestProject = 'frontend-node' | 'frontend-svelte-node' | 'frontend-dom'

export const frontendTestFileGlob = '**/*.test.ts'
export const svelteNodeTestFileGlob = '**/*.svelte-node.test.ts'
export const explicitDomTestFileGlobs = ['**/*.svelte.test.ts', '**/*.dom.test.ts'] as const
export const isolatedCompatibilityTestFiles = [
  'test/compat-harness/phase9CbsBaseline.test.ts',
  'test/compat-harness/phase9LuaFailureSemantics.test.ts',
] as const

// These pre-suffix suites are probe-backed DOM owners. Registering them
// explicitly avoids rename-only churn while still making new plain tests
// Node-default. Remove an entry when a fresh smaller-runtime probe passes or
// when its owner is renamed to an explicit DOM suffix.
export const legacyDomTestFiles = [
  'src/lib/ChatScreens/BackgroundDom.parserDependencies.test.ts',
  'src/lib/ChatScreens/Chat.customHtml.test.ts',
  'src/lib/ChatScreens/Chat.parserDependencies.test.ts',
  'src/lib/ChatScreens/ChatBody.parseMemo.test.ts',
  'src/lib/ChatScreens/DefaultChatScreen.composerDrafts.test.ts',
  'src/lib/ChatScreens/DefaultChatScreen.loadPages.test.ts',
  'src/lib/ChatScreens/PartialEditController.sharedHover.test.ts',
  'src/lib/ChatScreens/partialEditLayer.test.ts',
  'src/lib/ChatScreens/partialEditTouchTrigger.test.ts',
  'src/lib/Others/HypaV3Modal.resetRace.test.ts',
  'src/lib/Others/HypaV3Modal.serverReliability.test.ts',
  'src/lib/Others/HypaV3Modal/tag-manager-modal.test.ts',
  'src/lib/Others/ownerPaths.test.ts',
  'src/lib/Playground/PlaygroundSubtitle.test.ts',
  'src/lib/Setting/pickerGenerationSettings.test.ts',
  'src/lib/SideBars/chatGenerationSettingsControls.test.ts',
  'src/ts/__tests__/renderCostHarness.test.ts',
  'src/ts/__tests__/sendCloneCountProbe.test.ts',
  'src/ts/activeChatGenerationSettings.test.ts',
  'src/ts/agentPresets.test.ts',
  'src/ts/alert.test.ts',
  'src/ts/bootstrap.test.ts',
  'src/ts/characterCards.realmImport.test.ts',
  'src/ts/characterCommands.test.ts',
  'src/ts/characters.changeChar.test.ts',
  'src/ts/characters.exportChat.test.ts',
  'src/ts/characters.imageEmotion.test.ts',
  'src/ts/characters.importChat.test.ts',
  'src/ts/chatCommands.test.ts',
  'src/ts/chatFork.test.ts',
  'src/ts/compatibilityAdapters.test.ts',
  'src/ts/entryStartup.test.ts',
  'src/ts/globalApi.changeChatTo.test.ts',
  'src/ts/globalApi.downloadFile.test.ts',
  'src/ts/globalApi.fetchNative.test.ts',
  'src/ts/globalApi.getFileSrc.test.ts',
  'src/ts/globalApi.proxy.test.ts',
  'src/ts/globalApi.saveAssets.test.ts',
  'src/ts/gui/animation.test.ts',
  'src/ts/gui/colorscheme.test.ts',
  'src/ts/gui/guisize.test.ts',
  'src/ts/gui/heightMode.test.ts',
  'src/ts/gui/highlight.test.ts',
  'src/ts/gui/longtouch.test.ts',
  'src/ts/gui/modalBackdropDismiss.test.ts',
  'src/ts/gui/modalFocusTrap.test.ts',
  'src/ts/gui/viewportDebugOverlay.test.ts',
  'src/ts/gui/viewportScrollGuard.test.ts',
  'src/ts/gui/visualViewportCoordinator.test.ts',
  'src/ts/hotkey.navigation.test.ts',
  'src/ts/hotkey.preview.test.ts',
  'src/ts/hotkey.owner.test.ts',
  'src/ts/hubAdditionalHtml.test.ts',
  'src/ts/loadout.test.ts',
  'src/ts/media/compressImage/tests/lossyCompression.test.ts',
  'src/ts/moduleCommands.test.ts',
  'src/ts/readerProjectionLifecycle.test.ts',
  'src/ts/parser/tests/additionalAssetCache.test.ts',
  'src/ts/parser/tests/cbs/conditionals.test.ts',
  'src/ts/parser/tests/cbs/eachReinjection.test.ts',
  'src/ts/parser/tests/cbs/escapes.test.ts',
  'src/ts/parser/tests/cbs/history.test.ts',
  'src/ts/parser/tests/cbs/loop.test.ts',
  'src/ts/parser/tests/cbs/strings.test.ts',
  'src/ts/parser/tests/inlayBlobCache.test.ts',
  'src/ts/parser/tests/renderFastPaths.test.ts',
  'src/ts/persona.iconUpload.test.ts',
  'src/ts/persona.test.ts',
  'src/ts/plugins/apiV3/developMode.test.ts',
  'src/ts/plugins/apiV3/factory.test.ts',
  'src/ts/plugins/pluginIconSafety.test.ts',
  'src/ts/plugins/plugins.test.ts',
  'src/ts/process/__tests__/buildDescription.test.ts',
  'src/ts/process/__tests__/buildHistoryWindow.test.ts',
  'src/ts/process/__tests__/buildLorebookContext.test.ts',
  'src/ts/process/__tests__/buildMemoryWindow.test.ts',
  'src/ts/process/__tests__/buildPlainPromptSections.test.ts',
  'src/ts/process/__tests__/buildStaticPromptSections.test.ts',
  'src/ts/process/__tests__/charEmotionStore.test.ts',
  'src/ts/process/__tests__/command.owner.test.ts',
  'src/ts/process/__tests__/dispatchRequest.test.ts',
  'src/ts/process/__tests__/emotionFallbackEmbedding.test.ts',
  'src/ts/process/__tests__/emotionFallbackLlm.test.ts',
  'src/ts/process/__tests__/emotionFromResponse.test.ts',
  'src/ts/process/__tests__/formatHistoryMessage.test.ts',
  'src/ts/process/__tests__/igp.test.ts',
  'src/ts/process/__tests__/imggenStableDiff.test.ts',
  'src/ts/process/__tests__/lorebook.owner.test.ts',
  'src/ts/process/__tests__/nonStreamResponse.test.ts',
  'src/ts/process/__tests__/normalizeTemplate.test.ts',
  'src/ts/process/__tests__/orchestrateResponse.test.ts',
  'src/ts/process/__tests__/outputTrigger.test.ts',
  'src/ts/process/__tests__/preflightTemplateTokens.test.ts',
  'src/ts/process/__tests__/reattach.test.ts',
  'src/ts/process/__tests__/renderFinalPrompt.test.ts',
  'src/ts/process/__tests__/runStage4.test.ts',
  'src/ts/process/__tests__/sendChat.fixtures.serverBacked.test.ts',
  'src/ts/process/__tests__/sendChat.fixtures.test.ts',
  'src/ts/process/__tests__/sendChat.serverPreview.test.ts',
  'src/ts/process/__tests__/sendChatContext.test.ts',
  'src/ts/process/__tests__/sendChatErrors.test.ts',
  'src/ts/process/__tests__/sendChatPromptAssembly.lazyPromptTemplate.test.ts',
  'src/ts/process/__tests__/stage4Finalize.test.ts',
  'src/ts/process/__tests__/streamResponse.test.ts',
  'src/ts/process/__tests__/triggers.owner.test.ts',
  'src/ts/process/dynamicutils/pdf.test.ts',
  'src/ts/process/files/multisend.test.ts',
  'src/ts/process/files/tests/inlays.test.ts',
  'src/ts/process/index.svelte.stop.test.ts',
  'src/ts/process/mcp/internalClients.test.ts',
  'src/ts/process/mcp/mcp.test.ts',
  'src/ts/process/mcp/mcplib.test.ts',
  'src/ts/process/mcp/risuaccess/tests/characters.setCharacterInfo.test.ts',
  'src/ts/process/mcp/risuaccess/tests/modules.optimisticProjection.test.ts',
  'src/ts/process/mcp/risuaccess/tests/modules.test.ts',
  'src/ts/process/processzip.test.ts',
  'src/ts/process/regexDisplayReload.test.ts',
  'src/ts/process/request/clientContext.test.ts',
  'src/ts/process/request/tests/anthropicProfileOptions.test.ts',
  'src/ts/process/request/tests/cohereHordeOobaLegacyProfileOptions.test.ts',
  'src/ts/process/request/tests/durableGeneration.test.ts',
  'src/ts/process/request/tests/google.fastify.test.ts',
  'src/ts/process/request/tests/koboldProfileOptions.test.ts',
  'src/ts/process/request/tests/modelRoleRouting.test.ts',
  'src/ts/process/request/tests/ollamaProfileOptions.test.ts',
  'src/ts/process/request/tests/openaiProfileOptions.test.ts',
  'src/ts/process/request/tests/openaiResponsesLegacyProfileOptions.test.ts',
  'src/ts/process/request/tests/pluginProviderModelId.test.ts',
  'src/ts/process/request/tests/serverChat.test.ts',
  'src/ts/process/request/tests/serverPromptAssembly.test.ts',
  'src/ts/process/rerollNavigation.owner.test.ts',
  'src/ts/process/rerollNavigation.rollback.test.ts',
  'src/ts/process/rerollNavigation.test.ts',
  'src/ts/process/scriptings.test.ts',
  'src/ts/process/scripts.editdisplay.test.ts',
  'src/ts/process/scripts.importRegex.test.ts',
  'src/ts/process/scripts.regexCache.test.ts',
  'src/ts/process/serverBackedSendChat.findMessage.test.ts',
  'src/ts/process/serverGeneratedMessageTranslation.test.ts',
  'src/ts/process/triggers.clientBudget.test.ts',
  'src/ts/process/triggers.cloneCost.test.ts',
  'src/ts/process/triggers.regexMemo.test.ts',
  'src/ts/router.test.ts',
  'src/ts/server/activeWriterSession.test.ts',
  'src/ts/server/ownerMutationLifecycle.test.ts',
  'src/ts/server/characterShellHydration.test.ts',
  'src/ts/server/chatMessageHydration.test.ts',
  'src/ts/server/displaySources.test.ts',
  'src/ts/server/durableMutationTerminalRejection.test.ts',
  'src/ts/server/lifecycleRecovery.test.ts',
  'src/ts/server/promptTemplateHydration.test.ts',
  'src/ts/server/pushNotifications.test.ts',
  'src/ts/server/resourceRefresh.test.ts',
  'src/ts/server/routeResourceLoader.test.ts',
  'src/ts/server/settingsOwner.durable.svelte.test.ts',
  'src/ts/setting/languageSettingsData.test.ts',
  'src/ts/setting/utils.test.ts',
  'src/ts/storage/backup.test.ts',
  'src/ts/storage/database.downloadPreset.test.ts',
  'src/ts/storage/database.importPreset.test.ts',
  'src/ts/storage/database.resourceState.test.ts',
  'src/ts/translator/translator.html.test.ts',
  'src/ts/util.filePicker.test.ts',
  'src/ts/util.persona.test.ts',
] as const

const legacyDomTestFileSet = new Set<string>(legacyDomTestFiles)
const isolatedCompatibilityTestFileSet = new Set<string>(isolatedCompatibilityTestFiles)

export function frontendVitestProjectForFile(
  file: string,
  registeredDomFiles: ReadonlySet<string> = legacyDomTestFileSet,
): FrontendVitestProject | undefined {
  if (!file.endsWith('.test.ts')) return undefined
  if (isolatedCompatibilityTestFileSet.has(file)) return undefined
  if (file.endsWith('.svelte-node.test.ts')) return 'frontend-svelte-node'
  if (file.endsWith('.svelte.test.ts') || file.endsWith('.dom.test.ts') || registeredDomFiles.has(file)) {
    return 'frontend-dom'
  }
  return 'frontend-node'
}
