// Generated by util/generation-input-schema.ts. Do not edit.
import type {
  GenerationSettings,
  FastifyDatabase,
  DisplaySourceDatabase,
  GenerationPreflightInputs,
  ProviderGenerationSettings,
  MemoryGenerationSettings,
} from './serverTypes.js'
export type GenerationInputValidator<T> = {
  (value: unknown): value is T
  errors?: ReadonlyArray<{
    readonly instancePath: string
    readonly schemaPath: string
    readonly keyword: string
    readonly params: Readonly<Record<string, unknown>>
  }> | null
}
export declare const validateGenerationSettings: GenerationInputValidator<GenerationSettings>
export declare const validateFastifyDatabase: GenerationInputValidator<FastifyDatabase>
export declare const validateDisplaySourceDatabase: GenerationInputValidator<DisplaySourceDatabase>
export declare const validateGenerationPreflightInputs: GenerationInputValidator<GenerationPreflightInputs>
export declare const validateProviderGenerationSettings: GenerationInputValidator<ProviderGenerationSettings>
export declare const validateMemoryGenerationSettings: GenerationInputValidator<MemoryGenerationSettings>
export declare const generationInputValidatorMetadata: {
  readonly schemaDefinitions: 449
  readonly roots: 6
  readonly compiledAtBuildTime: true
}
