export const frontendCoreTestFiles = [
  'src/ts/bootstrap.resourceEvents.dom.test.ts',
  'src/ts/bootstrap.test.ts',
  'src/ts/characterCommands.test.ts',
  'src/ts/chatCommands.messages.dom.test.ts',
  'src/ts/plugins/pluginDatabaseBridge.core.test.ts',
  'src/ts/plugins/pluginPermissions.test.ts',
  'src/ts/process/__tests__/sendChat.fixtures.serverBacked.test.ts',
  'src/ts/process/__tests__/sendChatErrors.test.ts',
  'src/ts/process/__tests__/streamReplayGap.boundary.dom.test.ts',
  'src/ts/process/__tests__/streamResponse.test.ts',
  'src/ts/process/mcp/risuaccess/tests/characters.setCharacterInfo.test.ts',
  'src/ts/process/mcp/risuaccess/tests/modules.optimisticProjection.test.ts',
  'src/ts/process/request/tests/durableGeneration.test.ts',
  'src/ts/server/activeWriterSession.test.ts',
  'src/ts/server/characterDraft.svelte.test.ts',
  'src/ts/server/chatMessageHydration.completion.dom.test.ts',
  'src/ts/server/connectedTabIdentity.test.ts',
  'src/ts/server/durableMutationDispatch.test.ts',
  'src/ts/server/pendingMutationOutbox.test.ts',
  'src/ts/server/pendingMutationReplay.test.ts',
  'src/ts/server/resourceCache.test.ts',
  'src/ts/server/resourceInvalidation.test.ts',
  'src/ts/server/writerDraftRecovery.test.ts',
  'src/ts/storage/database.resourceState.test.ts',
] as const

export const serverCoreTestFiles = [
  'server/fastify/__tests__/activeWriter.test.ts',
  'server/fastify/__tests__/assetGc.test.ts',
  'server/fastify/__tests__/assetGcScheduling.test.ts',
  'server/fastify/__tests__/auth.test.ts',
  'server/fastify/__tests__/backups.test.ts',
  'server/fastify/__tests__/bardWikiLifecycle.test.ts',
  'server/fastify/__tests__/bardWikiRebuildHandler.test.ts',
  'server/fastify/__tests__/bardWikiVault.test.ts',
  'server/fastify/__tests__/chatDispatchProfileOptions.test.ts',
  'server/fastify/__tests__/chatOccupancy.test.ts',
  'server/fastify/__tests__/chatOccupancyEnforcement.test.ts',
  'server/fastify/__tests__/clientDiagnostics.test.ts',
  'server/fastify/__tests__/commandMessageFreeCeiling.test.ts',
  'server/fastify/__tests__/commandMutationReadNarrowing.test.ts',
  'server/fastify/__tests__/commandMutationReceipts.test.ts',
  'server/fastify/__tests__/commands.coldStorage.test.ts',
  'server/fastify/__tests__/commands.lorebooks.test.ts',
  'server/fastify/__tests__/commands.messages.test.ts',
  'server/fastify/__tests__/commands.modelProfiles.test.ts',
  'server/fastify/__tests__/commands.scripts.test.ts',
  'server/fastify/__tests__/commands.test.ts',
  'server/fastify/__tests__/databaseInitialization.test.ts',
  'server/fastify/__tests__/db.test.ts',
  'server/fastify/__tests__/durableGeneration.test.ts',
  'server/fastify/__tests__/events.test.ts',
  'server/fastify/__tests__/generation.chat.test.ts',
  'server/fastify/__tests__/generation.completion.test.ts',
  'server/fastify/__tests__/generationEffects.test.ts',
  'server/fastify/__tests__/generationFinalizationRetry.test.ts',
  'server/fastify/__tests__/generationInputLoaders.test.ts',
  'server/fastify/__tests__/generationOperationsStartup.test.ts',
  'server/fastify/__tests__/hub.test.ts',
  'server/fastify/__tests__/imageGeneration.test.ts',
  'server/fastify/__tests__/legacyDatabaseImport.test.ts',
  'server/fastify/__tests__/luaRuntime.test.ts',
  'server/fastify/__tests__/mcpOAuthRefresh.test.ts',
  'server/fastify/__tests__/messageStore.test.ts',
  'server/fastify/__tests__/missingDatabaseGuard.test.ts',
  'server/fastify/__tests__/pluginNetwork.test.ts',
  'server/fastify/__tests__/providerOperations.test.ts',
  'server/fastify/__tests__/providerTransport.test.ts',
  'server/fastify/__tests__/providerWireGoldens.core.test.ts',
  'server/fastify/__tests__/proxy.test.ts',
  'server/fastify/__tests__/realmImport.test.ts',
  'server/fastify/__tests__/remoteDiagnostics.test.ts',
  'server/fastify/__tests__/requestHistory.test.ts',
  'server/fastify/__tests__/requestTrace.test.ts',
  'server/fastify/__tests__/resourceReads.test.ts',
  'server/fastify/__tests__/risuSaveBoundedInflate.test.ts',
  'server/fastify/__tests__/risuSaveBundleImportRoute.test.ts',
  'server/fastify/__tests__/risuSaveCodec.test.ts',
  'server/fastify/__tests__/routeProtection.test.ts',
  'server/fastify/__tests__/staleInlineModelProfileSecrets.test.ts',
  'server/fastify/__tests__/stateInitializeRace.core.test.ts',
  'server/fastify/__tests__/tts.test.ts',
] as const

export const browserCoreTestFiles = [
  'server/fastify/browser-smoke/acceptedSendProtocol.spec.ts',
  'server/fastify/browser-smoke/coreLifecycle.spec.ts',
  'server/fastify/browser-smoke/coreLineage.spec.ts',
  'server/fastify/browser-smoke/coreOwnership.spec.ts',
  'server/fastify/browser-smoke/durableMutationRecovery.spec.ts',
  'server/fastify/browser-smoke/fastifyBrowserSmoke.spec.ts',
  'server/fastify/browser-smoke/importRestoreRecovery.spec.ts',
  'server/fastify/browser-smoke/rerollSwipePersistence.spec.ts',
] as const

export const CORE_BROWSER_TEST_TAG = '@core'
