export const phase1LazyBoundarySources = [
  'src/lib/Others/AlertComp.svelte',
  'src/lib/UI/Realm/LazyRealmPopUp.svelte',
  'src/lib/Others/GridCatalog.svelte',
  'src/lib/Others/BookmarkList.svelte',
  'src/lib/Setting/Settings.svelte',
  'src/lib/Setting/botpreset.svelte',
  'src/lib/Setting/listedPersona.svelte',
  'src/lib/SideBars/ChatGenerationTogglePresetDialog.svelte',
  'src/lib/Setting/Pages/CustomGUISettingMenu.svelte',
  'src/lib/Others/HypaV3Modal.svelte',
  'src/lib/Others/HypaV3Progress.svelte',
  'src/lib/UI/PopupList.svelte',
  'src/lib/Others/ProTools/EasyPanel.svelte',
  'src/lib/Others/PopupEditor.svelte',
  'src/lib/Others/LoadoutModal.svelte',
  'src/lib/Others/IrisModal.svelte',
  'src/lib/Others/CustomSidebarConfig.svelte',
  'src/lib/SideBars/CharConfig.svelte',
  'src/lib/SideBars/DevTool.svelte',
  'src/lib/Others/QuickSettingsGUI.svelte',
  'src/lib/Others/ChatList.svelte',
  'src/lib/Setting/Pages/Module/ModuleChatMenu.svelte',
  'src/lib/Playground/PlaygroundMenu.svelte',
  'src/lib/Setting/Pages/UserSettings.svelte',
  'src/lib/Setting/Pages/BotSettings.svelte',
  'src/lib/Setting/Pages/OtherBotSettings.svelte',
  'src/lib/Setting/Pages/BardWikiSettings.svelte',
  'src/lib/Setting/Pages/DisplaySettings.svelte',
  'src/lib/Setting/Pages/PluginSettings.svelte',
  'src/lib/Setting/Pages/AdvancedSettings.svelte',
  'src/lib/Setting/Pages/Communities.svelte',
  'src/lib/Setting/Pages/LazyGlobalLoreBookSettings.svelte',
  'src/lib/Setting/Pages/GlobalRegex.svelte',
  'src/lib/Setting/Pages/LanguageSettings.svelte',
  'src/lib/Setting/Pages/AccessibilitySettings.svelte',
  'src/lib/Setting/Pages/InteractionSettings.svelte',
  'src/lib/Setting/Pages/PersonaSettings.svelte',
  'src/lib/Setting/Pages/Module/ModuleSettings.svelte',
  'src/lib/Setting/Pages/PromptSettings.svelte',
  'src/lib/Setting/Pages/HotkeySettings.svelte',
  'src/lib/Setting/Pages/AgentPresetSettings.svelte',
  'src/lib/Setting/Pages/InputHookSettings.svelte',
  'src/lib/Setting/Pages/RequestHistorySettings.svelte',
  'src/lib/Setting/Pages/SourceCode.svelte',
  'src/lib/Setting/Pages/ThanksPage.svelte',
  'src/lib/Playground/PlaygroundEmbedding.svelte',
  'src/lib/Playground/PlaygroundTokenizer.svelte',
  'src/lib/Playground/PlaygroundSyntax.svelte',
  'src/lib/Playground/PlaygroundJinja.svelte',
  'src/lib/Playground/PlaygroundImageGen.svelte',
  'src/lib/Playground/PlaygroundParser.svelte',
  'src/lib/Playground/PlaygroundSubtitle.svelte',
  'src/lib/Playground/PlaygroundImageTrans.svelte',
  'src/lib/Playground/PlaygroundTranslation.svelte',
  'src/lib/Playground/PlaygroundMCP.svelte',
  'src/lib/Playground/PlaygroundDocs.svelte',
  'src/lib/Playground/PlaygroundInlayExplorer.svelte',
  'src/lib/Playground/ToolConversion.svelte',
  'src/ts/routeHandlers/settings.ts',
  'src/ts/routeHandlers/playground.ts',
  'src/ts/routeHandlers/character.ts',
] as const

export const phase1ProtectedInitialModules = {
  optionalSurface: phase1LazyBoundarySources,
  databaseImplementation: ['src/ts/storage/database.svelte.ts'],
  exportImplementation: [
    'src/ts/characterCards.ts',
    'src/ts/globalApi.svelte.ts',
    'src/ts/storage/exportAsDataset.ts',
    'src/ts/storage/risuSave.ts',
  ],
} as const

export const phase1ProtectedInitialModuleFragments = {
  exportImplementation: ['/node_modules/streamsaver/StreamSaver.js'],
} as const
