// Shared algorithm consumers and compatibility facades. Behavior lives beside each owner.
// Add consumer edges here when moving an algorithm across runtime boundaries.
export const requiredImports: Record<string, readonly string[]> = {
  './agentPresetRecords.js': [
    'packages/shared-core/src/agentPresetResolver.ts',
    'packages/shared-core/src/chatGenerationSettings.ts',
  ],
  './agentPresetResolver': ['src/ts/moduleActivation.ts'],
  './chatGenerationSettings.js': ['packages/shared-core/src/agentPresetResolver.ts'],
  './chatGenerationTogglePresetRecords.js': ['packages/shared-core/src/chatGenerationSettings.ts'],
  './chatMLRows.js': ['packages/shared-core/src/agentPresetRecords.ts'],
  './cbsCallbackMemo.js': ['server/fastify/src/prompt/assemble.ts', 'server/fastify/src/prompt/variables.ts'],
  './effectivePromptTemplate.js': ['packages/shared-core/src/cbsRegistry.ts'],
  './englishFixture.js': ['server/fastify/browser-smoke/lazyFirstOpen.spec.ts'],
  './fastBootstrapDirectLinks.js': ['server/fastify/browser-smoke/startupDirectLinks.spec.ts'],
  './modelProfileRecords.js': [
    'packages/shared-core/src/modelProfileResolver.ts',
    'packages/shared-core/src/presetSplit.ts',
  ],
  './localStopStrings.js': ['packages/shared-core/src/presetSplit.ts'],
  './modelProfileResolver.js': ['packages/shared-core/src/agentPresetResolver.ts'],
  './modelRoles.js': [
    'packages/shared-core/src/modelProfileRecords.ts',
    'packages/shared-core/src/modelProfileResolver.ts',
  ],
  './modelTypes.js': [
    'packages/shared-core/src/anthropicModels.ts',
    'packages/shared-core/src/googleModels.ts',
    'packages/shared-core/src/modelProfileRecords.ts',
    'packages/shared-core/src/modelProfileResolver.ts',
    'packages/shared-core/src/openaiModels.ts',
    'packages/shared-core/src/providerCapability.ts',
  ],
  './moduleActivation.js': ['packages/shared-core/src/chatGenerationSettings.ts'],
  './moduleIntegration.js': ['packages/shared-core/src/chatGenerationSettings.ts'],
  './personaModuleLinks': ['src/ts/moduleActivation.ts'],
  './promptSettings.js': ['packages/shared-core/src/settingsGroups.ts'],
  './promptTemplateNormalization.js': ['packages/shared-core/src/presetSplit.ts'],
  './providerCapability': ['src/ts/process/request/serverCompletion.ts'],
  './providerCapability.js': ['packages/shared-core/src/modelProfileResolver.ts'],
  './providerCredentialRecords.js': ['packages/shared-core/src/modelProfileResolver.ts'],
  './providerSecretMask.js': ['packages/shared-core/src/providerCapability.ts'],
  './triggerCompatibility.js': ['server/fastify/src/prompt/scripts.ts', 'server/fastify/src/prompt/triggers.ts'],
  '../src/prompt/triggerCompatibility.js': [
    'server/fastify/__tests__/phase9CompatibilityStructure.test.ts',
    'server/fastify/__tests__/triggerCompatibilityOwnership.test.ts',
    'server/fastify/__tests__/triggers.test.ts',
  ],
  '@risuai/shared-core/': [
    'server/fastify/src/prompt/cbsAdapter.ts',
    'server/fastify/src/prompt/promptVariablesBoot.ts',
    'server/fastify/src/prompt/variables.ts',
  ],
  '@risuai/shared-core/agent-lorebook-inputs': [
    'server/fastify/src/prompt/agentPresetExecution.ts',
    'src/ts/agentLorebookInputs.ts',
  ],
  '@risuai/shared-core/agent-only-lorebook': [
    'server/fastify/src/prompt/lorebook.ts',
    'src/lib/SideBars/LoreBook/LoreBookData.svelte',
    'src/ts/agentLorebookInputs.ts',
    'src/ts/process/lorebook.svelte.ts',
  ],
  '@risuai/shared-core/agent-preset-output-references': [
    'server/fastify/src/prompt/agentPresetExecution.ts',
    'server/fastify/src/prompt/variables.ts',
  ],
  '@risuai/shared-core/agent-preset-records': [
    'server/fastify/__tests__/agentPresetExecution.test.ts',
    'server/fastify/__tests__/assemble.test.ts',
    'server/fastify/src/commands/agentPresets.ts',
    'server/fastify/src/commands/presets.ts',
    'server/fastify/src/databaseDefaults.ts',
    'server/fastify/src/prompt/agentPresetErrors.ts',
    'server/fastify/src/prompt/agentPresetExecution.ts',
    'server/fastify/src/prompt/assemble.ts',
    'src/ts/agentPresetRecords.ts',
  ],
  '@risuai/shared-core/agent-preset-resolver': [
    'server/fastify/__tests__/agentPresetExecution.test.ts',
    'server/fastify/src/prompt/agentPresetExecution.ts',
    'server/fastify/src/prompt/assemble.ts',
    'server/fastify/src/prompt/effectiveGenerationConfig.ts',
    'src/ts/agentPresetResolver.ts',
  ],
  '@risuai/shared-core/anthropic-models': [
    'server/fastify/src/commands/modelProfiles.ts',
    'src/ts/model/providers/anthropic.ts',
  ],
  '@risuai/shared-core/calculation': [
    'server/fastify/src/prompt/cbsAdapter.ts',
    'server/fastify/src/prompt/triggerDataEffects.ts',
    'src/ts/process/infunctions.ts',
  ],
  '@risuai/shared-core/cbs-contracts': ['server/fastify/src/prompt/cbsCallbackMemo.ts'],
  '@risuai/shared-core/cbs-registry': ['src/ts/cbs.ts'],
  '@risuai/shared-core/browser-smoke': ['server/fastify/browser-smoke/globals.d.ts'],
  '@risuai/shared-core/chat-display-tail-count': [
    'server/fastify/src/databaseDefaults.ts',
    'src/ts/storage/database.svelte.ts',
  ],
  '@risuai/shared-core/local-stop-strings': [
    'server/fastify/src/commands/localStopStrings.ts',
    'server/fastify/src/databaseDefaults.ts',
    'server/fastify/src/repository.ts',
    'server/fastify/src/routes/commands.ts',
    'src/ts/storage/database.svelte.ts',
  ],
  '@risuai/shared-core/chat-generation-settings': [
    'server/fastify/__tests__/commandSingleRowPaths.test.ts',
    'server/fastify/__tests__/commands.test.ts',
    'server/fastify/src/chatGenerationSettingsStorage.ts',
    'server/fastify/src/commands/chats.ts',
    'server/fastify/src/prompt/effectiveGenerationConfig.ts',
    'server/fastify/src/risuSave/importSnapshot.ts',
    'server/fastify/src/routes/commands.ts',
    'src/ts/chatGenerationSettings.ts',
  ],
  '@risuai/shared-core/chat-generation-toggle-preset-records': [
    'server/fastify/src/routes/commands.ts',
    'src/ts/chatGenerationTogglePresetRecords.ts',
  ],
  '@risuai/shared-core/chat-load-pages': [
    'server/fastify/src/databaseDefaults.ts',
    'src/lib/ChatScreens/DefaultChatScreen.loadPages.ts',
    'src/lib/ChatScreens/DefaultChatScreen.svelte',
    'src/ts/server/chatMessageHydration.svelte.ts',
    'src/ts/server/routeResourceLoader.ts',
    'src/ts/storage/database.svelte.ts',
  ],
  '@risuai/shared-core/chat-page': ['server/fastify/src/commands/chats.ts', 'src/ts/chatCommands.ts'],
  '@risuai/shared-core/chatml-rows': [
    'server/fastify/src/prompt/agentPresetExecution.ts',
    'server/fastify/src/prompt/templates.ts',
    'src/lib/Setting/Pages/AgentEditorDrawer.svelte',
    'src/ts/parser/chatML.ts',
  ],
  '@risuai/shared-core/default-hotkeys': ['server/fastify/src/databaseDefaults.ts', 'src/ts/defaulthotkeys.ts'],
  '@risuai/shared-core/default-prompt-settings': [
    'server/fastify/src/databaseDefaults.ts',
    'src/ts/storage/defaultPrompts.ts',
  ],
  '@risuai/shared-core/effective-prompt-template': [
    'server/fastify/src/prompt/staticSections.ts',
    'server/fastify/src/prompt/templates.ts',
    'src/lib/Setting/Pages/OtherBotSettings.svelte',
    'src/ts/process/promptAssembly/effectivePromptTemplate.ts',
    'src/ts/process/promptAssembly/normalizeTemplate.ts',
    'src/ts/process/templates/templateCheck.ts',
    'src/ts/utilState.ts',
  ],
  '@risuai/shared-core/google-models': [
    'server/fastify/src/commands/modelProfiles.ts',
    'src/ts/model/providers/google.ts',
  ],
  '@risuai/shared-core/history-slots': [
    'server/fastify/src/translation/rawMessageTranslation.ts',
    'src/lib/ChatScreens/DefaultChatScreen.svelte',
    'src/ts/process/inputHooks.ts',
  ],
  '@risuai/shared-core/inlay-tokens': ['server/fastify/src/memorySummaryPrompt.ts', 'src/ts/process/memory/hypav3.ts'],
  '@risuai/shared-core/internal-reasoning': [
    'server/fastify/src/generation/stripCoT.ts',
    'server/fastify/src/prompt/agentPresetExecution.ts',
    'server/fastify/src/translation/rawMessageTranslation.ts',
    'src/ts/translator/translator.ts',
  ],
  '@risuai/shared-core/legacy-openai-model-aliases': [
    'server/fastify/src/generation/openai.ts',
    'server/fastify/src/generation/openaiLegacyInstruct.ts',
    'server/fastify/src/generation/openaiResponses.ts',
    'src/ts/process/request/openAI/requests.ts',
  ],
  '@risuai/shared-core/lore-hash': [
    'server/fastify/src/prompt/cbsAdapter.ts',
    'server/fastify/src/prompt/lorebook.ts',
    'src/ts/util.ts',
  ],
  '@risuai/shared-core/mcp-identifier': [
    'server/fastify/src/commands/modules.ts',
    'src/ts/process/mcp/mcpIdentifier.ts',
  ],
  '@risuai/shared-core/memory-model-capability': [
    'server/fastify/src/commands/modelProfiles.ts',
    'server/fastify/src/memorySummaryModel.ts',
    'src/ts/model/memoryModelCapability.ts',
  ],
  '@risuai/shared-core/model-profile-records': [
    'server/fastify/src/commands/modelProfiles.ts',
    'server/fastify/src/commands/presets.ts',
    'server/fastify/src/commands/providerCredentials.ts',
    'server/fastify/src/commands/splitPresets.ts',
    'server/fastify/src/databaseDefaults.ts',
    'server/fastify/src/prompt/effectiveGenerationConfig.ts',
    'server/fastify/src/routes/commands.ts',
    'src/ts/model/modelProfileRecords.ts',
  ],
  '@risuai/shared-core/model-profile-resolver': [
    'server/fastify/__tests__/phase7CompatibilityStructure.test.ts',
    'src/ts/model/modelProfileResolver.ts',
  ],
  '@risuai/shared-core/model-roles': [
    'server/fastify/src/commands/modelProfiles.ts',
    'server/fastify/src/commands/presets.ts',
    'server/fastify/src/commands/splitPresets.ts',
    'server/fastify/src/databaseDefaults.ts',
    'server/fastify/src/ollamaCloudToolProxy.ts',
    'server/fastify/src/prompt/luaRuntime.ts',
    'server/fastify/src/routes/commands.ts',
    'server/fastify/src/routes/generation.ts',
    'src/lib/ChatScreens/Suggestion.svelte',
    'src/lib/Others/AllSeperateParameters.svelte',
    'src/lib/Others/IrisModal.svelte',
    'src/lib/Others/ProTools/EasyPanel.svelte',
    'src/lib/Playground/PlaygroundSubtitle.svelte',
    'src/lib/Setting/Pages/Model/ModelPresetList.svelte',
    'src/lib/Setting/Pages/Model/ModelProfileList.svelte',
    'src/lib/Setting/Pages/Model/ModelProfileRoleList.svelte',
    'src/lib/Setting/Pages/Model/ModelRoleEditor.svelte',
    'src/lib/Setting/Pages/Model/ModelRoleList.svelte',
    'src/lib/Setting/Pages/Model/ModelSettingsShell.svelte',
    'src/ts/model/modelProfileMutations.ts',
    'src/ts/model/modelProfileUiState.ts',
    'src/ts/process/__fixtures__/mocks/serverCompletionFetch.ts',
    'src/ts/process/request/shared.ts',
    'src/ts/server/commands.ts',
    'src/ts/storage/database.svelte.ts',
  ],
  '@risuai/shared-core/model-types': [
    'server/fastify/__tests__/assemble.test.ts',
    'server/fastify/__tests__/chatDispatchProfileOptions.test.ts',
    'server/fastify/__tests__/commands.test.ts',
    'server/fastify/__tests__/databaseDefaults.test.ts',
    'server/fastify/__tests__/generation.chat.test.ts',
    'server/fastify/__tests__/generation.completion.test.ts',
    'server/fastify/__tests__/modelProfileResolver.server.test.ts',
    'server/fastify/__tests__/phase7CompatibilityStructure.test.ts',
    'server/fastify/__tests__/providerCapabilityRoute.test.ts',
    'server/fastify/__tests__/providerMessages.test.ts',
    'server/fastify/__tests__/splitPresets.test.ts',
    'server/fastify/__tests__/tokenizerConfig.test.ts',
    'server/fastify/src/commands/modelProfiles.ts',
    'server/fastify/src/databaseDefaults.ts',
    'server/fastify/src/generation/providerMessages.ts',
    'server/fastify/src/ollamaCloudToolProxy.ts',
    'server/fastify/src/prompt/chatDispatch.ts',
    'server/fastify/src/prompt/promptScope.ts',
    'server/fastify/src/prompt/tokenizerConfig.ts',
    'server/fastify/src/prompt/variables.ts',
    'src/ts/model/types.ts',
  ],
  '@risuai/shared-core/module-activation': [
    'server/fastify/__tests__/phase10CompatibilityStructure.test.ts',
    'server/fastify/src/prompt/modules.ts',
    'src/ts/moduleActivation.ts',
  ],
  '@risuai/shared-core/module-integration': [
    'server/fastify/src/prompt/effectiveGenerationConfig.ts',
    'src/ts/moduleActivation.ts',
  ],
  '@risuai/shared-core/mutation-certificates': [
    'server/fastify/__tests__/commands.test.ts',
    'server/fastify/src/commands/personas.ts',
    'server/fastify/src/commands/scriptDefinitions.ts',
    'src/ts/personaMutationCertificate.ts',
    'src/ts/server/scriptDefinitionMutations.ts',
  ],
  '@risuai/shared-core/openai-models': [
    'server/fastify/src/commands/modelProfiles.ts',
    'server/fastify/src/prompt/chatDispatch.ts',
    'src/ts/model/providers/openai.ts',
  ],
  '@risuai/shared-core/parse-key-value': [
    'server/fastify/src/prompt/chatVarDefaults.ts',
    'src/ts/util/parseKeyValue.ts',
  ],
  '@risuai/shared-core/preset-split': [
    'server/fastify/__tests__/phase5CompatibilityStructure.test.ts',
    'server/fastify/src/commands/splitPresets.ts',
    'server/fastify/src/databaseDefaults.ts',
    'server/fastify/src/displaySourceService.ts',
    'server/fastify/src/memorySummarizeJobHandler.ts',
    'server/fastify/src/prompt/effectiveGenerationConfig.ts',
    'server/fastify/src/routes/commands.ts',
    'src/ts/presetSplit.ts',
  ],
  '@risuai/shared-core/prompt-block-role': [
    'server/fastify/src/prompt/templates.ts',
    'src/ts/process/promptBlockRole.ts',
  ],
  '@risuai/shared-core/prompt-info-snapshot': [
    'server/fastify/src/prompt/effectiveGenerationConfig.ts',
    'src/ts/promptInfo.ts',
  ],
  '@risuai/shared-core/prompt-settings': [
    'server/fastify/src/commands/prompts.ts',
    'src/lib/Setting/Pages/BotSettings.svelte',
  ],
  '@risuai/shared-core/prompt-template-normalization': [
    'server/fastify/src/commands/prompts.ts',
    'src/ts/process/promptTemplateNormalization.ts',
  ],
  '@risuai/shared-core/provider-capability': [
    'server/fastify/__tests__/phase7CompatibilityStructure.test.ts',
    'server/fastify/src/prompt/chatDispatch.ts',
    'src/ts/process/request/providerCapability.ts',
  ],
  '@risuai/shared-core/provider-credential-records': [
    'server/fastify/src/commands/modelProfiles.ts',
    'server/fastify/src/commands/providerCredentials.ts',
    'server/fastify/src/databaseDefaults.ts',
    'server/fastify/src/routes/commands.ts',
    'src/ts/model/providerCredentialRecords.ts',
  ],
  '@risuai/shared-core/provider-secret-mask': [
    'server/fastify/__tests__/chatDispatchProfileOptions.test.ts',
    'server/fastify/src/commands/providerCredentials.ts',
    'server/fastify/src/providerSecrets.ts',
    'src/ts/providerSecretMask.ts',
  ],
  '@risuai/shared-core/punctuation': [
    'server/fastify/src/prompt/assemble.ts',
    'server/fastify/src/routes/generationChat.ts',
    'src/ts/util.ts',
  ],
  '@risuai/shared-core/regex-output-size-limit': [
    'server/fastify/src/databaseDefaults.ts',
    'server/fastify/src/prompt/boundedRegex.ts',
    'server/fastify/src/prompt/scripts.ts',
    'server/fastify/src/routes/commands.ts',
    'src/ts/process/regexWorkerRuntime.ts',
    'src/ts/process/scripts.ts',
    'src/ts/setting/advancedSettingsData.ts',
    'src/ts/storage/database.svelte.ts',
  ],
  '@risuai/shared-core/resource-manifest': ['server/fastify/browser-smoke/fastBootstrapDirectLinks.ts'],
  '@risuai/shared-core/router-route': ['server/fastify/browser-smoke/fastBootstrapDirectLinks.ts'],
  '@risuai/shared-core/risuchat-parser': ['src/ts/parser/risuChatParser.ts'],
  '@risuai/shared-core/risuchat-parser-helpers': [
    'server/fastify/src/displaySourceService.ts',
    'server/fastify/src/prompt/cbsAdapter.ts',
    'server/fastify/src/prompt/scripts.ts',
    'server/fastify/src/prompt/variables.ts',
    'server/fastify/src/routes/generationChat.ts',
    'src/ts/parser/risuChatParserHelpers.ts',
  ],
  '@risuai/shared-core/script-model-overrides': [
    'server/fastify/src/commands/characters.ts',
    'server/fastify/src/commands/modules.ts',
    'server/fastify/src/databaseDefaults.ts',
    'server/fastify/src/prompt/luaRuntime.ts',
    'server/fastify/src/prompt/moduleDescriptors.ts',
    'src/lib/UI/ScriptModelOverrideSelectors.svelte',
    'src/ts/process/modules.ts',
    'src/ts/process/scriptings.ts',
    'src/ts/process/triggers.ts',
    'src/ts/server/characterDraft.svelte.ts',
    'src/ts/server/commands.ts',
    'src/ts/storage/database.svelte.ts',
  ],
  '@risuai/shared-core/settings-groups': [
    'server/fastify/__tests__/phase3CompatibilityStructure.test.ts',
    'server/fastify/__tests__/phase5CompatibilityStructure.test.ts',
    'server/fastify/__tests__/settingsGroupParity.test.ts',
    'server/fastify/src/risuSave/importSnapshot.ts',
    'src/ts/server/settingsGroups.ts',
  ],
  '@risuai/shared-core/translator-pipeline': [
    'server/fastify/src/translation/rawMessageTranslation.ts',
    'src/ts/translator/pipeline.ts',
  ],
  '@risuai/shared-core/translator-presets': [
    'server/fastify/src/commands/translatorPresets.ts',
    'server/fastify/src/databaseDefaults.ts',
    'src/ts/translator/presets.ts',
  ],
  '@risuai/shared-core/trigger-compatibility': [
    'server/fastify/src/prompt/triggerCompatibility.ts',
    'server/fastify/__tests__/triggerCompatibilityOwnership.test.ts',
    'src/ts/process/triggerServerSupport.ts',
  ],
  '@risuai/protocol/startup-telemetry': [
    'server/fastify/browser-smoke/startupCachePopulationMatrix.spec.ts',
    'server/fastify/browser-smoke/startupRecoveryIntegrationMatrix.spec.ts',
  ],
  'src/ts/process/triggerServerSupport': [
    'src/lib/SideBars/Scripts/RegexData.svelte',
    'src/lib/SideBars/Scripts/TriggerList.svelte',
    'src/lib/SideBars/Scripts/TriggerV2List.svelte',
    'src/lib/SideBars/Scripts/triggerV2Import.test.ts',
  ],
  fflate: ['src/ts/translator/presets.ts'],
  'msgpackr/index-no-eval': ['src/ts/translator/presets.ts'],
}

export const forwardingFacades: Record<string, readonly [module: string, exports: readonly string[]]> = {
  'server/fastify/src/prompt/triggerCompatibility.ts': ['@risuai/shared-core/trigger-compatibility', ['*']],
  'src/ts/agentPresetResolver.ts': ['@risuai/shared-core/agent-preset-resolver', ['*']],
  'src/ts/chatGenerationSettings.ts': ['@risuai/shared-core/chat-generation-settings', ['*']],
  'src/ts/model/modelProfileResolver.ts': ['@risuai/shared-core/model-profile-resolver', ['*']],
  'src/ts/model/providers/anthropic.ts': ['@risuai/shared-core/anthropic-models', ['AnthropicModels']],
  'src/ts/model/providers/google.ts': ['@risuai/shared-core/google-models', ['GoogleModels']],
  'src/ts/model/providers/openai.ts': ['@risuai/shared-core/openai-models', ['OpenAIModels']],
  'src/ts/presetSplit.ts': ['@risuai/shared-core/preset-split', ['*']],
  'src/ts/process/promptBlockRole.ts': ['@risuai/shared-core/prompt-block-role', ['*']],
  'src/ts/process/request/providerCapability.ts': ['@risuai/shared-core/provider-capability', ['*']],
  'src/ts/process/triggerServerSupport.ts': ['@risuai/shared-core/trigger-compatibility', ['*']],
  'src/ts/routerRoute.ts': ['@risuai/shared-core/router-route', ['*']],
  'src/ts/server/resourceManifest.ts': ['@risuai/shared-core/resource-manifest', ['*']],
  'src/ts/translator/pipeline.ts': ['@risuai/shared-core/translator-pipeline', ['*']],
}

export const packageExports: Record<string, string> = {
  './local-stop-strings': './src/localStopStrings.ts',
  './agent-preset-resolver': './src/agentPresetResolver.ts',
  './anthropic-models': './src/anthropicModels.ts',
  './chat-generation-settings': './src/chatGenerationSettings.ts',
  './google-models': './src/googleModels.ts',
  './hypa-v3-preset-selection-identity': './src/hypaV3PresetSelectionIdentity.ts',
  './model-profile-records': './src/modelProfileRecords.ts',
  './model-profile-resolver': './src/modelProfileResolver.ts',
  './module-activation': './src/moduleActivation.ts',
  './openai-models': './src/openaiModels.ts',
  './persona-selection-identity': './src/personaSelectionIdentity.ts',
  './preset-split': './src/presetSplit.ts',
  './prompt-block-role': './src/promptBlockRole.ts',
  './prompt-template-normalization': './src/promptTemplateNormalization.ts',
  './provider-capability': './src/providerCapability.ts',
  './translator-pipeline': './src/translatorPipeline.ts',
  './translator-presets': './src/translatorPresets.ts',
  './trigger-compatibility': './src/triggerCompatibility.ts',
}

export const retiredPaths = [
  'src/ts/agentPresetReferences.ts',
  'src/ts/chatDisplayTailCount.ts',
  'src/ts/chatLoadPages.ts',
  'src/ts/model/legacyOpenAIModelAliases.ts',
  'src/ts/model/modelRoles.ts',
  'src/ts/model/scriptModelOverrides.ts',
  'src/ts/moduleIntegration.ts',
  'src/ts/parser/chatMLCore.ts',
  'src/ts/process/internalReasoning.ts',
  'src/ts/promptSettings.ts',
  'src/ts/regexOutputSizeLimit.ts',
  'src/ts/translator/historySlots.ts',
  'src/ts/util/inlayTokens.ts',
  'src/ts/util/loreHash.ts',
  'src/ts/util/punctuation.ts',
] as const
