import type { ServerModule } from './prompt/moduleDescriptors.js'
import type { GenerationSettings, FastifyCharacter, FastifyChat } from './prompt/serverTypes.js'

/** Every finite input requires an explicit owner. Adding a typed reader field
 * without classifying it here is a compile error. Unknown import extensions are
 * not implicitly made generation inputs. */
type Owner = 'fixed' | 'runtime' | 'outside'

export const GenerationSettingsOwners = {
  acceptedCredentialPolicy: 'outside',
  adaptiveThinkingEffort: 'fixed',
  additionalParams: 'fixed',
  additionalPrompt: 'fixed',
  agentPresetDefaultId: 'fixed',
  agentPresets: 'fixed',
  agents: 'fixed',
  aiModel: 'fixed',
  applyAdditionalParamsToAll: 'fixed',
  autofillRequestUrl: 'fixed',
  automaticCachePoint: 'fixed',
  banCharacterset: 'fixed',
  bardWiki: 'fixed',
  bias: 'fixed',
  chainOfThought: 'fixed',
  claude1HourCaching: 'fixed',
  claudeAPIKey: 'fixed',
  cohereAPIKey: 'fixed',
  complexRegexCompatibilityMode: 'fixed',
  complexRegexDisplayTimeoutMs: 'outside',
  complexRegexInputTimeoutMs: 'fixed',
  complexRegexOutputTimeoutMs: 'fixed',
  customAPIFormat: 'fixed',
  customFlags: 'fixed',
  customModels: 'fixed',
  customProxyRequestModel: 'fixed',
  customTokenizer: 'fixed',
  dallEQuality: 'fixed',
  deepseekReasoningEffort: 'fixed',
  deepseekThinkingType: 'fixed',
  descriptionPrefix: 'fixed',
  dynamicAssets: 'fixed',
  dynamicAssetsEditDisplay: 'outside',
  dynamicOutput: 'fixed',
  echoDelay: 'fixed',
  echoMessage: 'fixed',
  enableCustomFlags: 'fixed',
  enabledModules: 'fixed',
  extractJson: 'fixed',
  fallbackModels: 'fixed',
  fallbackWhenBlankResponse: 'fixed',
  falLora: 'fixed',
  falLoraScale: 'fixed',
  falModel: 'fixed',
  forceReplaceUrl: 'fixed',
  formatingOrder: 'fixed',
  frequencyPenalty: 'fixed',
  generationSeed: 'fixed',
  genTime: 'fixed',
  globalChatVariables: 'fixed',
  globalNote: 'fixed',
  globalscript: 'fixed',
  google: 'fixed',
  googleClaudeTokenizing: 'fixed',
  gptVisionQuality: 'fixed',
  groupOtherBotRole: 'fixed',
  groupTemplate: 'fixed',
  halfStreaming: 'fixed',
  hordeConfig: 'fixed',
  hypaCustomSettings: 'fixed',
  hypaModel: 'fixed',
  hypaV3: 'fixed',
  hypaV3Key: 'fixed',
  hypaV3Presets: 'fixed',
  igpPrompt: 'fixed',
  ImagenAspectRatio: 'fixed',
  ImagenImageSize: 'fixed',
  ImagenModel: 'fixed',
  ImagenPersonGeneration: 'fixed',
  instructChatTemplate: 'fixed',
  jailbreak: 'fixed',
  jailbreakToggle: 'fixed',
  JinjaTemplate: 'fixed',
  jsonSchema: 'fixed',
  jsonSchemaEnabled: 'fixed',
  koboldURL: 'fixed',
  localStopStrings: 'fixed',
  loreBookDepth: 'fixed',
  loreBookToken: 'fixed',
  mainPrompt: 'fixed',
  mancerHeader: 'fixed',
  maxContext: 'fixed',
  maxResponse: 'fixed',
  min_p: 'fixed',
  mistralKey: 'fixed',
  modelPresets: 'fixed',
  modelPresetsId: 'fixed',
  modelProfiles: 'fixed',
  modelRoleProfiles: 'fixed',
  modelRoles: 'fixed',
  modelRuntimeDefaults: 'fixed',
  modelTools: 'fixed',
  moduleIntergration: 'fixed',
  modules: 'fixed',
  NAII2I: 'fixed',
  NAIImgConfig: 'fixed',
  NAIImgModel: 'fixed',
  nanogptKey: 'fixed',
  nanogptProvider: 'fixed',
  nanogptRequestModel: 'fixed',
  nanogptRequestModelName: 'fixed',
  nanogptSubscriptionState: 'fixed',
  nanogptUseSubscriptionEndpoint: 'fixed',
  newOAIHandle: 'fixed',
  OaiCompAPIKeys: 'fixed',
  OAIPrediction: 'fixed',
  ollamaApiKey: 'fixed',
  ollamaCloudModel: 'fixed',
  ollamaCloudModelName: 'fixed',
  ollamaModel: 'fixed',
  ollamaModelName: 'fixed',
  ollamaModelSource: 'fixed',
  ollamaRequestFormat: 'fixed',
  ollamaThinkingMode: 'fixed',
  ollamaURL: 'fixed',
  ooba: 'fixed',
  openAIFlexProcessing: 'fixed',
  openAIKey: 'fixed',
  openrouterFallback: 'fixed',
  openrouterKey: 'fixed',
  openrouterMiddleOut: 'fixed',
  openrouterProvider: 'fixed',
  openrouterRequestModel: 'fixed',
  outputImageModal: 'fixed',
  personaPrompt: 'fixed',
  personas: 'fixed',
  PresensePenalty: 'fixed',
  presetRegex: 'fixed',
  promptInfoInsideChat: 'fixed',
  promptPreprocess: 'fixed',
  promptPresets: 'fixed',
  promptPresetsId: 'fixed',
  promptSettings: 'fixed',
  promptTemplate: 'fixed',
  promptTextInfoInsideChat: 'fixed',
  providerCredentials: 'fixed',
  proxyKey: 'fixed',
  reasoningEffort: 'fixed',
  regexOutputSizeLimitMiB: 'fixed',
  removeIncompleteResponse: 'fixed',
  repetition_penalty: 'fixed',
  requestHistoryLimit: 'fixed',
  requestRetrys: 'fixed',
  reverseProxyOobaArgs: 'fixed',
  reverseProxyOobaMode: 'fixed',
  sdConfig: 'fixed',
  sdProvider: 'fixed',
  selectedHypaV3PresetId: 'fixed',
  selectedPersona: 'fixed',
  selectedPersonaId: 'fixed',
  seperateModels: 'fixed',
  seperateModelsForAxModels: 'fixed',
  seperateParameters: 'fixed',
  seperateParametersByModel: 'fixed',
  seperateParametersEnabled: 'fixed',
  stabilityModel: 'fixed',
  stabllityStyle: 'fixed',
  streamGeminiThoughts: 'fixed',
  strictJsonSchema: 'fixed',
  systemContentReplacement: 'fixed',
  systemRoleReplacement: 'fixed',
  temperature: 'fixed',
  templateDefaultVariables: 'fixed',
  textgenWebUIBlockingURL: 'fixed',
  thinkingTokens: 'fixed',
  thinkingType: 'fixed',
  top_a: 'fixed',
  top_k: 'fixed',
  top_p: 'fixed',
  ttsAutoSpeech: 'outside',
  username: 'fixed',
  useSayNothing: 'fixed',
  useStreaming: 'fixed',
  verbosity: 'fixed',
  vertexClientEmail: 'fixed',
  vertexPrivateKey: 'fixed',
  vertexRegion: 'fixed',
  voyageApiKey: 'fixed',
  wavespeedImage: 'fixed',
  subModel: 'fixed',
  language: 'fixed',
  userIcon: 'fixed',
  userNote: 'fixed',
  customPromptTemplateToggle: 'fixed',
} as const satisfies Record<keyof GenerationSettings, Owner>

export const FastifyCharacterOwners = {
  type: 'fixed',
  name: 'fixed',
  firstMessage: 'fixed',
  desc: 'fixed',
  notes: 'fixed',
  chats: 'fixed',
  chatFolders: 'outside',
  chatPage: 'fixed',
  viewScreen: 'fixed',
  bias: 'fixed',
  emotionImages: 'fixed',
  globalLore: 'fixed',
  chaId: 'fixed',
  sdData: 'fixed',
  customscript: 'fixed',
  utilityBot: 'fixed',
  exampleMessage: 'fixed',
  creatorNotes: 'fixed',
  systemPrompt: 'fixed',
  postHistoryInstructions: 'fixed',
  alternateGreetings: 'fixed',
  tags: 'fixed',
  creator: 'fixed',
  characterVersion: 'fixed',
  personality: 'fixed',
  scenario: 'fixed',
  firstMsgIndex: 'fixed',
  replaceGlobalNote: 'fixed',
  additionalText: 'fixed',
  defaultVariables: 'fixed',
  triggerscript: 'fixed',
  inlayViewScreen: 'fixed',
  newGenData: 'fixed',
  displayName: 'fixed',
  image: 'fixed',
  nickname: 'fixed',
  supaMemory: 'fixed',
  additionalAssets: 'fixed',
  lowLevelAccess: 'fixed',
  modules: 'fixed',
  scriptModelOverrides: 'fixed',
  scriptstate: 'fixed',
  loreSettings: 'fixed',
  depth_prompt: 'fixed',
  backgroundHTML: 'fixed',
  backgroundCSS: 'outside',
  removedQuotes: 'fixed',
  escapeOutput: 'fixed',
  doNotChangeSeperateModels: 'fixed',
  prebuiltAssetCommand: 'fixed',
  prebuiltAssetStyle: 'fixed',
  prebuiltAssetExclude: 'fixed',
  extentions: 'outside',
} as const satisfies Record<keyof FastifyCharacter, Owner>

export const FastifyChatOwners = {
  message: 'runtime',
  note: 'fixed',
  name: 'fixed',
  localLore: 'fixed',
  generationSettings: 'fixed',
  sdData: 'fixed',
  lastMemory: 'runtime',
  hypaContextTruncationAcknowledged: 'runtime',
  suggestMessages: 'outside',
  isStreaming: 'outside',
  scriptstate: 'runtime',
  modules: 'fixed',
  id: 'fixed',
  bindedPersona: 'fixed',
  fmIndex: 'fixed',
  selectedDraftHookId: 'outside',
  translatorPresetId: 'fixed',
  autoTranslate: 'fixed',
  autoTranslateBotOnly: 'fixed',
  bilingualDisplay: 'outside',
  bilingualEmphasis: 'outside',
  hypaV3Data: 'runtime',
  folderId: 'outside',
  lastDate: 'outside',
  bookmarks: 'outside',
  bookmarkNames: 'outside',
  pinned: 'outside',
} as const satisfies Record<keyof FastifyChat, Owner>

/** Translation has a record-shaped API; enumerate its additional policy reads. */
export const translationPolicyFields = [
  'translatorType',
  'translator',
  'translatorInputLanguage',
  'translatorHistoryMaxTokens',
  'translatorSendTextAsIs',
  'translatorExcludeThoughts',
  'translatorPresetId',
  'translatorPresets',
  'translatorPrompt',
  'translatorMaxResponse',
  'deeplOptions',
  'deeplXOptions',
  'autoTranslate',
  'autoTranslateBotOnly',
  'autoTranslateCachedOnly',
  'autoTranslateNotificationDeferCapSeconds',
] as const

export function selectFixedFields(
  value: Record<string, unknown>,
  owners: Record<string, Owner>,
): Record<string, unknown> {
  return Object.fromEntries(
    Object.keys(owners)
      .filter((key) => owners[key] === 'fixed' && Object.hasOwn(value, key))
      .map((key) => [key, value[key]]),
  )
}

export const ModuleOwners = {
  name: 'fixed',
  description: 'fixed',
  lorebook: 'fixed',
  regex: 'fixed',
  cjs: 'outside',
  trigger: 'fixed',
  id: 'fixed',
  lowLevelAccess: 'fixed',
  scriptModelOverrides: 'fixed',
  hideIcon: 'outside',
  backgroundEmbedding: 'fixed',
  assets: 'fixed',
  namespace: 'fixed',
  customModuleToggle: 'fixed',
  mcp: 'fixed',
  folderId: 'outside',
} as const satisfies Record<keyof ServerModule, Owner>
