export type UiCompatibilityOwner =
  | 'route-state'
  | 'character-command'
  | 'chat-structure-command'
  | 'message-command'
  | 'generation-operation'
  | 'input-hook-operation'
  | 'translation-operation'
  | 'speech-operation'
  | 'read-only-export'
  | 'local-ui'

export interface UiCompatibilityControlGroup {
  controls: readonly string[]
  owner: UiCompatibilityOwner
  source: string
}

export const phase4RouteInventory = {
  routeKinds: ['home', 'settings', 'playground', 'inlay', 'grid', 'character', 'not-found'],
  rootSegments: ['character', 'characters', 'grid', 'inlay', 'inlays', 'playground', 'settings'],
  examples: [
    { path: '/', kind: 'home' },
    { path: '/settings', kind: 'settings' },
    { path: '/settings/persona/persona-a', kind: 'settings' },
    { path: '/settings/context-agent', kind: 'not-found' },
    { path: '/settings/unknown-section', kind: 'settings' },
    { path: '/playground', kind: 'playground' },
    { path: '/playground/unknown-tool', kind: 'playground' },
    { path: '/inlay', kind: 'inlay' },
    { path: '/grid', kind: 'grid' },
    { path: '/characters', kind: 'grid' },
    { path: '/character/char-a', kind: 'character' },
    { path: '/character/char-a/chat-a', kind: 'character' },
    { path: '/characters/char-a/chats', kind: 'character' },
    { path: '/characters/char-a/chats/chat-a', kind: 'character' },
    { path: '/not-a-route', kind: 'not-found' },
  ],
  settingsSections: [
    'accessibility',
    'advanced',
    'advanced-settings',
    'agent-preset',
    'agent-presets',
    'backup',
    'backup-restore',
    'bardwiki',
    'bot',
    'bot-preset',
    'botpreset',
    'chat-bot',
    'chatbot',
    'communities',
    'community',
    'display',
    'global-lorebook',
    'global-regex',
    'hotkey',
    'hotkeys',
    'input-hooks',
    'language',
    'lore',
    'lorebook',
    'memory',
    'model',
    'model-settings',
    'models',
    'module',
    'modules',
    'other-bots',
    'otherbots',
    'persona',
    'plugin',
    'plugins',
    'preset',
    'presets',
    'prompt',
    'prompt-preset',
    'prompt-presets',
    'prompt-settings',
    'prompt-template',
    'prompts',
    'regex',
    'request-history',
    'requesthistory',
    'source-code',
    'sourcecode',
    'supporter',
    'thanks',
    'user',
  ],
  playgroundTools: [
    'cbs',
    'chat',
    'docs',
    'embedding',
    'image-gen',
    'image-generation',
    'image-trans',
    'image-translation',
    'inlay',
    'inlays',
    'jinja',
    'mcp',
    'menu',
    'parser',
    'subtitle',
    'subtitles',
    'syntax',
    'tokenizer',
    'tool-conversion',
    'tools',
    'translation',
    'translator',
  ],
} as const

export const phase4ControlInventory: readonly UiCompatibilityControlGroup[] = [
  {
    source: 'src/App.svelte',
    owner: 'route-state',
    controls: ['testid:route-resource-error', 'testid:route-resource-loading'],
  },
  {
    source: 'src/lib/ConversationShell.svelte',
    owner: 'route-state',
    controls: ['responsive-shell:shared-sidebar-dialog'],
  },
  {
    source: 'src/lib/UI/GUI/SideBarArrow.svelte',
    owner: 'route-state',
    controls: ['sidebar-toggle:collapse', 'sidebar-toggle:expand'],
  },
  {
    source: 'src/lib/SideBars/Sidebar.svelte',
    owner: 'route-state',
    controls: ['sidebar-tab:character', 'sidebar-tab:chat', 'testid:sidebar-developer-tools-button'],
  },
  {
    source: 'src/lib/SideBars/SideChatList.svelte',
    owner: 'route-state',
    controls: ['chat-action:back-to-chat-list'],
  },
  {
    source: 'src/lib/SideBars/ChatSelectionButton.svelte',
    owner: 'route-state',
    controls: ['chat-action:select'],
  },
  {
    source: 'src/lib/SideBars/SideChatList.svelte',
    owner: 'chat-structure-command',
    controls: [
      'chat-action:create',
      'chat-action:create-folder',
      'chat-action:delete',
      'chat-action:edit',
      'chat-action:folder-delete',
      'chat-action:folder-edit',
      'chat-action:import',
      'chat-action:organize',
      'chat-action:toggle-folder',
    ],
  },
  {
    source: 'src/lib/SideBars/SideChatList.svelte',
    owner: 'read-only-export',
    controls: ['chat-action:export', 'chat-action:export-all'],
  },
  {
    source: 'src/lib/SideBars/SideChatList.svelte',
    owner: 'local-ui',
    controls: [
      'chat-action:bookmarks',
      'chat-action:branches',
      'chat-action:edit-list',
      'chat-action:folder-options',
      'chat-action:options',
    ],
  },
  {
    source: 'src/lib/Others/ChatList.svelte',
    owner: 'route-state',
    controls: ['chat-action:close', 'chat-action:open'],
  },
  {
    source: 'src/lib/Others/ChatList.svelte',
    owner: 'chat-structure-command',
    controls: ['chat-action:create', 'chat-action:delete', 'chat-action:edit', 'chat-action:import'],
  },
  {
    source: 'src/lib/Others/ChatList.svelte',
    owner: 'read-only-export',
    controls: ['chat-action:export'],
  },
  {
    source: 'src/lib/Others/GridCatalog.svelte',
    owner: 'route-state',
    controls: ['grid-action:back'],
  },
  {
    source: 'src/lib/SideBars/CharacterCatalogView.svelte',
    owner: 'route-state',
    controls: ['grid-action:open'],
  },
  {
    source: 'src/lib/Others/GridCatalog.svelte',
    owner: 'character-command',
    controls: ['grid-action:delete', 'grid-action:delete-permanent', 'grid-action:restore'],
  },
  {
    source: 'src/lib/Others/BookmarkList.svelte',
    owner: 'message-command',
    controls: ['bookmark-action:remove', 'bookmark-action:rename'],
  },
  {
    source: 'src/lib/Mobile/MobileCharacters.svelte',
    owner: 'route-state',
    controls: ['mobile-character-action:open'],
  },
  {
    source: 'src/lib/Mobile/MobileCharacters.svelte',
    owner: 'character-command',
    controls: ['mobile-character-action:create'],
  },
  {
    source: 'src/lib/ChatScreens/Chat.svelte',
    owner: 'message-command',
    controls: [
      'message-action:bookmark',
      'message-action:branch',
      'message-action:disable-above',
      'message-action:edit',
      'message-action:remove',
      'message-action:switch-role',
      'message-action:toggle-disabled',
    ],
  },
  {
    source: 'src/lib/ChatScreens/Chat.svelte',
    owner: 'generation-operation',
    controls: ['message-action:reroll', 'message-action:unreroll'],
  },
  {
    source: 'src/lib/ChatScreens/Chat.svelte',
    owner: 'local-ui',
    controls: ['message-action:copy'],
  },
  {
    source: 'src/lib/ChatScreens/Chat.svelte',
    owner: 'translation-operation',
    controls: ['message-action:translate'],
  },
  {
    source: 'src/lib/ChatScreens/Chat.svelte',
    owner: 'speech-operation',
    controls: ['message-action:tts'],
  },
  {
    source: 'src/lib/ChatScreens/DefaultChatScreen.svelte',
    owner: 'generation-operation',
    controls: [
      'testid:accepted-send-recovery',
      'testid:accepted-send-retry',
      'testid:default-chat-cancel-button',
      'testid:default-chat-preparing-button',
      'testid:default-chat-send-button',
      'testid:generation-reattach-failure',
      'testid:generation-reattach-last-error',
      'testid:generation-reattach-refresh',
      'testid:generation-reattach-retry',
      'testid:generation-reattach-stop',
      'testid:generation-stop-completion-saving',
      'testid:generation-stop-failed',
      'testid:generation-stop-refresh',
      'testid:generation-stop-retry',
      'testid:generation-stop-saving-partial',
    ],
  },
  {
    source: 'src/lib/ChatScreens/DefaultChatScreen.svelte',
    owner: 'input-hook-operation',
    controls: [
      'testid:composer-draft-persistence-error',
      'testid:default-chat-btw-button',
      'testid:default-chat-btw-dismiss',
      'testid:default-chat-btw-result',
      'testid:default-chat-convert-button',
      'testid:default-chat-draft-area',
      'testid:default-chat-draft-input',
      'testid:default-chat-draft-send',
    ],
  },
  {
    source: 'src/lib/ChatScreens/DefaultChatScreen.svelte',
    owner: 'local-ui',
    controls: [
      'testid:chat-display-dependency-error',
      'testid:chat-hydration-error',
      'testid:default-chat-composer',
      'testid:default-chat-menu-button',
      'testid:default-chat-open-bardwiki',
      'testid:default-chat-open-chat-list',
      'testid:default-chat-open-modules',
      'testid:default-chat-overflow-menu',
      'testid:default-chat-pin-button',
      'testid:default-chat-screenshot-button',
      'testid:floating-chat-input-button',
      'testid:floating-chat-input-go-to-bottom',
      'testid:floating-chat-input-hide',
      'testid:floating-chat-pin-button',
    ],
  },
] as const

export const phase4ResponsiveShellClassification = {
  sourceObligation: 'fork-parity',
  baselineControl: 'betaMobileGUI',
  baselineShell: ['MobileHeader', 'MobileBody', 'MobileFooter'],
  currentShell: 'shared-sidebar-dialog',
  currentBreakpoint: 'window.innerWidth <= 1024',
  signedDecisionId: 'ORC-DECISION-060',
  disposition: 'signed-divergence',
} as const
